# Generated by Django 5.1.4 on 2025-01-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(unique=True)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=5)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastprintapp.kategori')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastprintapp.status')),
            ],
        ),
    ]
